### ISSUE TITLE
Sconsx not found on travis

### ISSUE THREAD

**Issue by christian34** [openalea-incubator/caribu#17]
The travis build is currently failing due to import error of sconsx. any clue ?

**Comment by artzet-s** [comment]
Hello christian, 

It's certainly due to the github version. You need to replace the follow lines in the .travis.yml  : 

"
  - pip install git+https://github.com/openalea/deploy
  - pip install git+https://github.com/openalea/sconsx
"
by 

"
  - conda install -c openalea openalea.deploy
  - conda install -c openalea openalea.sconsx
"

I propose this, because I reproduce the travis error on my machine with :
 
` conda create -n test_caribu_1 python -y
 activate test_caribu_1
 pip install git+https://github.com/openalea/deploy
 pip install git+https://github.com/openalea/sconsx
 python -c "from openalea.sconsx import config, environ"`
=>
Resulting a `ImportError: No module named SCons.Script`

And no error with the release version on conda :

` conda create -n test_caribu_2 python -y
 activate test_caribu_2
 conda install -c openalea openalea.deploy
 conda install -c openalea openalea.sconsx
 python -c "from openalea.sconsx import config, environ"`

**Comment by artzet-s** [comment]
I directly submit a pull request with this modification

**Comment by artzet-s** [comment]
After running with this modification on travis via the PR, that failed after with : 

`error: [Errno 2] No such file or directory: 'build-scons/bin'`

So maybe is not a good solution, you need the sconsx expert @pradal

**Comment by christian34** [comment]
Cool ! unfortunately, some lib errors at install now appears : any (new) clue ?

**Comment by artzet-s** [comment]
resolve with PR #18
